export interface Property {
  id: string;
  title: string;
  description: string;
  location: string;
  locationNodeId?: string;
  countyId?: string;
  countyName?: string;
  locationSource?: string;
  locationAccuracy?: string;
  price: number;
  listingType?: "FOR_RENT" | "FOR_SALE" | "SHORT_STAY";
  pricePeriod?: "MONTH" | "WEEK" | "NIGHT" | "ONE_TIME";
  shortStayMinNights?: number;
  shortStayMaxNights?: number;
  cleaningFee?: number;
  securityDeposit?: number;
  maxGuests?: number;
  images: string[];
  bedrooms: number;
  bathrooms: number;
  area?: number;
  amenities?: string[];
  phoneNumber?: string;
  propertyType?: string;
  status?: string;
  isSponsored?: boolean;
  promotionId?: string;
  promotionLabel?: string;
  promotionBoost?: number;
  latitude?: number;
  longitude?: number;
  distanceKm?: number;
}
